# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployInfrastructure
  jobs:
  - job: DeployWithTerraform
    steps:
    - script: terraform init
      displayName: 'Terraform init'

    - script: terraform apply -refresh-only -auto-approve 
      displayName: 'Terraform apply'
